### ISSUE TITLE
Invisible Boots

### ISSUE THREAD

**Issue by TripleShades** [LoneStarF13/LoneStar#175]
## Reproduction:
Pick Desert Combat Boots in your Character Select Loadout.
Find out you have invisible boots.
Wear them anyways.

(They're missing the inventory icon)

**Comment by Cythisiax** [comment]
fixed icon_state "erin_boot" no longer in sprite, changed to "laced"

**Comment by TripleShades** [comment]
Just realized you didn't actually fix any of these so I'm reopening them.

**Comment by Cythisiax** [comment]
Yeah I closed the PR, I don't do PRs anymore.
